name: food_delievery_restaurants
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  country_picker: ^2.0.25
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  page_transition: ^2.1.0
  provider: ^6.1.2
  image_picker: ^1.0.8
  uuid: ^4.4.0
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  carousel_slider: ^4.2.1
  geolocator: ^11.0.0
  flutter_geofire: ^2.0.3
  flutter_styled_toast: ^2.2.1
  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  os: true
  image_path: "assets/images/appIcon/logo.png"
  adaptive_icon_foreground: "assets/images/appIcon/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/categories/
    - assets/images/splashScreenImage/
    - assets/images/appIcon/logo.png
  fonts: 
    - family: UberMoveMedium
      fonts: 
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts: 
        - asset: assets/fonts/UberMoveBold.otf