// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWbcGqcQH68yKwGpJlV9jvcsmVAD-wJ0',
    appId: '1:105302244532:android:843e05a1d405ec3980abe1',
    messagingSenderId: '105302244532',
    projectId: 'covefood-52c23',
    storageBucket: 'covefood-52c23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hMA9vGGP1_vTmwGki-BE-kvYVrKw5NM',
    appId: '1:105302244532:ios:740f615d6470271680abe1',
    messagingSenderId: '105302244532',
    projectId: 'covefood-52c23',
    storageBucket: 'covefood-52c23.appspot.com',
    androidClientId: '105302244532-imb99i7tj9jn2vrrtunvi28f1a039thb.apps.googleusercontent.com',
    iosClientId: '105302244532-4j73g5nergd095dukr36ipghjkou376n.apps.googleusercontent.com',
    iosBundleId: 'com.example.covefoodDomiciliario',
  );
}
